name: 自动发送工作日报

on:
  schedule:
    -  cron: '18 3 * * *'
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码与文件
        uses: actions/checkout@v3

      - name: 设置 Python 运行环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install openpyxl

      - name: 执行发信
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
        run: python send_daily.py
